### ISSUE TITLE
Outputs count X is greater than max allowed 60.

### ISSUE THREAD

**Issue by NijsTom** [dougmoscrop/serverless-plugin-split-stacks#15]
Have been running into the 200 stack limit and my solution to it was manually maintaining a swagger doc file and manually updating it. Attempted to use this plugin and ran into an issue listed below, if you need any more information from me, just ask. Cheers

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: [serverless-plugin-split-stacks]: Summary: 99 resources migrated in to 3 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:
Serverless: [serverless-plugin-split-stacks]:    - (root): 167
Serverless: [serverless-plugin-split-stacks]:    - APINestedStack: 97
Serverless: [serverless-plugin-split-stacks]:    - PermissionsNestedStack: 1
Serverless: [serverless-plugin-split-stacks]:    - VersionsNestedStack: 1
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (37.36 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....
Serverless: Operation failed!

  Serverless Error ---------------------------------------

  An error occurred: APINestedStack - Template format error: Outputs count 81 is greater than max allowed 60.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           6.10.2
     Serverless Version:     1.23.0

**Comment by dougmoscrop** [comment]
Unfortunately this is another CloudFormation limitation. We might be able to make some of this done via a Map:: parameter instead. The hope is that we can revisit splitting per function, which also might help here.

If you want to share your cloudformation .json files, please feel free - I will have a look, but make sure you've sanitized them of anything sensitive (anonymize stuff, remove secrets/etc).

**Comment by dougmoscrop** [comment]
I pushed a branch, of mostly untested code (sorry!) that initiate sub-stack splitting if outoupts reaches 60. You can try it by changing the plugin version in your package.json to: `github:dougmoscrop/serverless-plugin-split-stacks#split_on_outputs` -- let me know if this works for you, @NijsTom @yogumanivannan @brunocascio

**Comment by PorterK** [comment]
Hi @dougmoscrop I got this error with the branch

```
An error occurred: VersionsNestedStack - Embedded stack arn:aws:cloudformation:us-east-1:550875873656:stack/lumatic-backend-production-VersionsNestedStack-1P3BEQTT5F1ZV/0406c0c0-1282-11e8-ab14-50d5ca6e60ae was not successfully created: The following resource(s) failed to create: [UpdatePointsPurchaseLambdaVersionfggxcTFuhEuslE3bzXs8vr4lnByQ6TREWEYqcCCXE, GetOrganizationByIdLambdaVersionXOcyrSOEXMyPqywBzqjf6iif7BPFU1kmaf0dXQVDzQ, UpdateLocationLambdaVersionqcpNZHDBcwmVvp3WXxqgzPl98fMdJr3MZhlbVWwNUx8, GetLocationByIdLambdaVersionqMyMDu5xs3RhaJAPACBnN2jucGEki4saATOSvKmA1g, SendSignupEmailLambdaVersionaDKEFOLMztt0vgAgyv7lTs29L08XDiFlquSmlFGdFec, ListOrganizationLambdaVersion1yZqsnMR8MJ1V4vxEZoJKi8zCAcXF5HK9Bcwz9dI, GetPointsPurchaseByIdLambdaVersion9Lb5MZ2iZdUrYDvrUnWHeEiFotxYaNmbbnuhe4Zr7o, CreateOrganizationLambdaVersionmlWlcLgjO3a5PIEPxRBOXvwRpVVELRS1lqnS3sQFY, ListUsersLambdaVersiondVl13bYLZfWlLOyEia3opUhitBwA4JyNkW0FabKIuJM, CreateEventLambdaVersionFQJ1qrOAd8mC0ltKhwcp7w0Q6heVP5xx63nDpY5Jxdk, CreateUserLambdaVersion9JL85M0dYwEa67cpqZhYFHh5eG6wi8dqw.
```

**Comment by JTOracle** [comment]
this did not work for me. I switched my package.json to this and am still getting the above mentioned error.

**Comment by dfloresgonz** [comment]
any solutions to this error?

**Comment by dougmoscrop** [comment]
You can try setting:

```yml
provider:
  versionFunctions: false
```

https://github.com/serverless/serverless/blob/2fe45421133d25ec81093744752f852aa672a795/lib/plugins/aws/package/compile/functions/index.js#L386

**Comment by toryadams** [comment]
I will get back to on this. Just wanted to let you know I saw this.

**Comment by toryadams** [comment]
versionFunctions fixed me issue.

**Comment by SpencerGreene** [comment]
I'm having this exact problem and setting versionFunctions: false makes no difference.  Any theories why that might be?

**Comment by MacMcIrish** [comment]
If anyone is having issues with the `APINestedStack` having too many outputs, we were able to resolve this by _further_ separating the ApiGateway resources into more stacks grouped together with the api methods.
So a lambda function for `GET /foo` would be broken into at least the following 3 stacks:

`FooNestedStack` (contains the lamdba function `foo`)
`FooResourcesNestedStack` (contains the `AWS::ApiGateway::Method` and `AWS::ApiGateway::Resource` cloudformation resources)
`APINestedStack` (contains and exports the reference to the Api Gateway)

The issue for us was the APINestedStack needed to export the `ApiGateway::Resources` so they could be referenced by the `ApiGateway::Methods`. Grouping them together removes the need for the export, which resolves the output limit.

**Comment by ivanhoe1982** [comment]
@MacMcIrish how exactly did you do this split? can you point me to the right part of the plugin and what you modified? I've been banging my head on this topic for a couple of hours now, still without success

**Comment by dougmoscrop** [comment]
You should not have to modify the plugin, just the custom split-stacks.js file which lets you totally customize the 'routing' logic.

That said, I'd welcome any PRs that add more intelligent splitting for these things that affect many users

**Comment by ivanhoe1982** [comment]
@dougmoscrop I have written a strategy in stacks-map.js by overloading  ServerlessPluginSplitStacks.resolveMigration which did somethign similar to 'per-type' strategy...  until I hit the 60 outputs limit for AWS::ApiGateway::Resource (which I did hit in per-type strategy too); any attempts at further splitting this result in 'circular dependency' warning and that's why I would love to see a custom strategy written by someone smarter than me - it would probably help me diagnose what I'm doing wrong

**Comment by juvaly** [comment]
I have a similar issue with Parameter count: 
`Template format error: Parameter count 89 is greater than max allowed 60`

Any ideas how to resolve?

**Comment by dougmoscrop** [comment]
You have to refactor your stacks to split them more aggressively using stacks-map

**Comment by juvaly** [comment]
I did. I tried splitting them by Alphabet :)
But the max 60 parameters seems to be global and not per stack.
The 89 count I get in the error is the sum of parameters in all nested
stacks.

**Comment by dougmoscrop** [comment]
I've been meaning to write a helper utility to explain stack summaries but for now you have to look at the compiled cloudformation (stack-update.json) and see which stack has a huge # of params. It's def not "total" but per-nested stack

**Comment by juvaly** [comment]
You are right. The split did the job, and the error that followed was
unrelated to the Parameters. I was too tired to notice :/
Thanks for the help!

**Comment by dougmoscrop** [comment]
The support for splitting when Outputs reaches 60 landed in 1.9.0, however I realized just now that it assumes each resource only adds one Output, so in theory it could go 1, 2, 3... 59, then have a resource that adds two outputs and it would blow up.  Supporting that scenario is a bit more involved so I will leave this open, and consider the Output support that currently exists as hopeful/optimistic

**Comment by vicary** [comment]
> I pushed a branch, of mostly untested code (sorry!) that initiate sub-stack splitting if outputs reaches 60. You can try it by changing the plugin version in your package.json to: `github:dougmoscrop/serverless-plugin-split-stacks#split_on_outputs` -- let me know if this works for you, @NijsTom @yogumanivannan @brunocascio

This method temporarily solves our problem, but our AppSync stack is growing fast. Hope it doesn't hit the limitations soon.

I have function versions disabled.

**Comment by martineca** [comment]
Hi all! I am a bit confused, if we are getting this error but from the main stack, the one that holds links to all the nested stacks does that mean that our only option is to split the project into more .yml files? If yes then isn't that limit of 200 resources not valid if you have mainly lambdas as each lambda created new output line meaning maximum lambdas = 60?

**Comment by dougmoscrop** [comment]
yes, you have to turn off version functions for that

**Comment by martineca** [comment]
@dougmoscrop  I've turned off 'versionFunctions' but because there are 61 lambdas in the .yml file I am still hitting the 61 outputs limit. Am I missing something? I also tried with split-on-output version but from what I understood that will work only for the nested stacks, not the main one.

**Comment by martineca** [comment]
I was passing --versionFunction true as cli variable on each deploy but that is being read as a string instead of a boolean. Just changed it to false in the .yml file and it works as expected now. Thanks!

**Comment by gmagella-ca** [comment]
> You can try setting:
> 
> ```yaml
> provider:
>   versionFunctions: false
> ```
> 
> https://github.com/serverless/serverless/blob/2fe45421133d25ec81093744752f852aa672a795/lib/plugins/aws/package/compile/functions/index.js#L386

Fantastic! this should be documented a bit better in the docs, or even in the treated error message from Serverless. Helped me! Thanks

**Comment by chan1600** [comment]
added 

provider:
  versionFunctions: false

it does not work for me
